### ISSUE TITLE
Integration with coffeeify

### ISSUE THREAD

**Issue by maxparm** [wallabyjs/wallabify#4]
I can get my code working with browserify however when I had the coffeeify plugin, wallaby does not seem to use the right files. 

Looking in the cached files, I can see my `example1-test.coffee` file is transformed to `example1-test.coffee.bro.js`. In the wallaby console, it tells me _0 failing tests, 0 passing_.

Here is my `wallaby.js` config file

```
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
    }
    , function (b) {
        return b.transform(require('coffeeify'));
    }
);

module.exports = function (w) {
    return {
        files: [
            {pattern: 'static/js/example1.js', load: false}
        ],
        tests: [
            {pattern: 'static/js/example1-test.coffee', load: false}
        ],
        compilers: {},
        debug: true,
        postprocessor: wallabyPostprocessor,

        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

Thanks in advance for the help.

**Comment by ArtemGovorov** [comment]
With CoffeeScript, you need to use a [CoffeeScript compiler](/docs/integration/coffeescript.html) instead of the transform with wallaby.js, because with the transform in the postprocessor, it is too late for wallaby to instrument the resulting JavaScript. I have added [the note about it to the docs](http://wallabyjs.com/docs/integration/browserify.html#browserify-options). 

So the config like this one (with a default CoffeeScript compiler) should work for you:

``` JavaScript
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({});

module.exports = function (w) {
    return {
        files: [
            {pattern: 'static/js/example1.js', load: false}
        ],
        tests: [
            {pattern: 'static/js/example1-test.coffee', load: false}
        ],
        debug: true,
        postprocessor: wallabyPostprocessor,

        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

As a bonus, using a compiler is faster than using a transform.
